global.author = "HendraOfficial";
global.key_free = ["henfree"];
global.key_premium = ["hendra"];
global.limit_free = "100";
global.limit_premium = "Unlimited";
global.mongo_Db = "mongodb+srv://P-store:<password>@p-store.yyaopug.mongodb.net/?retryWrites=true&w=majority";
global.recaptcha_key_1 = "6LcHhD4mAAAAABNrbkdrap9Gg9R_nVmksj4kcWbV";
global.recaptcha_key_2 = "6LcHhD4mAAAAAEpdQpkfsY5D1Gf8k9UpBzjbm_ZO";
global.my_email = "gvgameindonesia@gmail.com";
global.my_email_password = "Budeaxasb13";
global.activation_token = "hendra";
global.port = 3000